vich_uploader:
    db_driver: orm

    mappings:
       deal_images:
           uri_prefix: /images/deals
           upload_destination: '%kernel.project_dir%/public/images/deals'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
